source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'rails'
gem 'pg'
gem 'puma'
gem 'webpacker'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'google-api-client'
gem 'excon'
gem 'nokogiri'
gem 'bootstrap'
gem 'simple_form'

group :development, :test do
  gem 'pry'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'annotate'
  gem 'rspec-rails'
  gem 'factory_bot'
end

group :development do
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end
